name: 'Verify Typescript'

on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Build and Lint
        run: |
          npm ci
          cd packages/pac-man-map-generator
          npm run lint
          npm run build
          cd ../example
          npm run lint
          npm run build
